//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILDMS.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SILDMS.Model.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Data has already been posted.
        /// </summary>
        public static string B099 {
            get {
                return ResourceManager.GetString("B099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Purchase Order is Invalid..
        /// </summary>
        public static string B101 {
            get {
                return ResourceManager.GetString("B101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Purchase Order is not released..
        /// </summary>
        public static string B102 {
            get {
                return ResourceManager.GetString("B102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items are blocked or deleted / No valid item exists in the PO..
        /// </summary>
        public static string B103 {
            get {
                return ResourceManager.GetString("B103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string B104 {
            get {
                return ResourceManager.GetString("B104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents already scanned..
        /// </summary>
        public static string B105 {
            get {
                return ResourceManager.GetString("B105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required document missing.
        /// </summary>
        public static string E118 {
            get {
                return ResourceManager.GetString("E118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save.
        /// </summary>
        public static string E401 {
            get {
                return ResourceManager.GetString("E401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete.
        /// </summary>
        public static string E402 {
            get {
                return ResourceManager.GetString("E402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Update..
        /// </summary>
        public static string E403 {
            get {
                return ResourceManager.GetString("E403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Validation Failed..
        /// </summary>
        public static string E404 {
            get {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Already Exist..
        /// </summary>
        public static string E405 {
            get {
                return ResourceManager.GetString("E405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocurrency Occured. Please Try Again Later..
        /// </summary>
        public static string E406 {
            get {
                return ResourceManager.GetString("E406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User suspended..
        /// </summary>
        public static string E407 {
            get {
                return ResourceManager.GetString("E407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password..
        /// </summary>
        public static string E408 {
            get {
                return ResourceManager.GetString("E408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not authorized to perform this action. .
        /// </summary>
        public static string E409 {
            get {
                return ResourceManager.GetString("E409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same user name already exist. Please try with different name..
        /// </summary>
        public static string E410 {
            get {
                return ResourceManager.GetString("E410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column name match with property name. Please upload valid excel file..
        /// </summary>
        public static string E411 {
            get {
                return ResourceManager.GetString("E411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill stop failed..
        /// </summary>
        public static string E412 {
            get {
                return ResourceManager.GetString("E412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill open failed..
        /// </summary>
        public static string E413 {
            get {
                return ResourceManager.GetString("E413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add atleast one document..
        /// </summary>
        public static string E414 {
            get {
                return ResourceManager.GetString("E414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option to deliver the message..
        /// </summary>
        public static string E415 {
            get {
                return ResourceManager.GetString("E415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Already Received for Clearing.
        /// </summary>
        public static string E416 {
            get {
                return ResourceManager.GetString("E416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clearing document(s) found..
        /// </summary>
        public static string E417 {
            get {
                return ResourceManager.GetString("E417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill is already stopped..
        /// </summary>
        public static string E418 {
            get {
                return ResourceManager.GetString("E418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill is already open..
        /// </summary>
        public static string E419 {
            get {
                return ResourceManager.GetString("E419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document(s) found for disbursement..
        /// </summary>
        public static string E420 {
            get {
                return ResourceManager.GetString("E420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to proceed..
        /// </summary>
        public static string E421 {
            get {
                return ResourceManager.GetString("E421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document you are trying to scan is not recognized by the system..
        /// </summary>
        public static string E422 {
            get {
                return ResourceManager.GetString("E422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documents needed for vendor EFT registration (Request Letter, Cheque), is not defined in the system..
        /// </summary>
        public static string E423 {
            get {
                return ResourceManager.GetString("E423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concern GL Already Exist..
        /// </summary>
        public static string E424 {
            get {
                return ResourceManager.GetString("E424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concern GL not found..
        /// </summary>
        public static string E425 {
            get {
                return ResourceManager.GetString("E425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque is already disbursed..
        /// </summary>
        public static string E426 {
            get {
                return ResourceManager.GetString("E426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque does not exist..
        /// </summary>
        public static string E427 {
            get {
                return ResourceManager.GetString("E427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete. This tracking no. is already parked..
        /// </summary>
        public static string E428 {
            get {
                return ResourceManager.GetString("E428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete. This tracking no. is already posted..
        /// </summary>
        public static string E429 {
            get {
                return ResourceManager.GetString("E429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete. This tracking no. is already cleared..
        /// </summary>
        public static string E430 {
            get {
                return ResourceManager.GetString("E430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document you requested are not currently available..
        /// </summary>
        public static string E431 {
            get {
                return ResourceManager.GetString("E431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a valid booth user..
        /// </summary>
        public static string E432 {
            get {
                return ResourceManager.GetString("E432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a Box..
        /// </summary>
        public static string E433 {
            get {
                return ResourceManager.GetString("E433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box limit exceed. .
        /// </summary>
        public static string E434 {
            get {
                return ResourceManager.GetString("E434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a Box..
        /// </summary>
        public static string E435 {
            get {
                return ResourceManager.GetString("E435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Already exist in Vendor TT.
        /// </summary>
        public static string EP406 {
            get {
                return ResourceManager.GetString("EP406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string S201 {
            get {
                return ResourceManager.GetString("S201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated Successfully..
        /// </summary>
        public static string S202 {
            get {
                return ResourceManager.GetString("S202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully..
        /// </summary>
        public static string S203 {
            get {
                return ResourceManager.GetString("S203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill successfully stopped..
        /// </summary>
        public static string S204 {
            get {
                return ResourceManager.GetString("S204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill successfully opened..
        /// </summary>
        public static string S205 {
            get {
                return ResourceManager.GetString("S205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the selected bill are received by the system..
        /// </summary>
        public static string S206 {
            get {
                return ResourceManager.GetString("S206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data found..
        /// </summary>
        public static string S207 {
            get {
                return ResourceManager.GetString("S207", resourceCulture);
            }
        }
    }
}
